### ISSUE TITLE
Importing .nessus and .burp files

### ISSUE THREAD

**Issue by Simon-Davies** [softrams/bulwark#740]
Do you support importing .nessus and .burp files?

**Comment by Whamo12** [comment]
@Simon-Davies Thanks for reaching out.  Currently, we do not support importing .nessus or .burp files.   If this is a feature you would like to request, please provide the following information:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
